version: '3'

services:
  palworld-01:
    image: yutsuku/palworld:latest
    container_name: palworld-01
    restart: unless-stopped
    ports:
      - "8211:8211/udp"
    volumes:
      - "./data:/opt/data/Pal/Saved"
    environment:
      - SERVER_NAME="Palworld"
      - ADMIN_PASSWORD=""
